server:
  port: 8000
spring:
  profiles:
    active: prod #测试 本地环境dev 生成环境 prod
  jackson:
    time-zone: GMT+8
    data:
      redis:
        repositories:
          enabled: false
  mail:
    host: smtp.163.com
    username: 邮箱用户
    password: 邮箱密码
    default-encoding: UTF-8

mybatis:
  type-aliases-package: me.jiahao.modules.*.entity
  mapper-locations: classpath*:me.jiahao.modules.*.mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

mail:
  fromMail:
    addr: jiahao_pan1@163.com


# 登录相关配置
login:
  #  验证码
  login-code:
    #  验证码类型配置 查看 LoginProperties 类
    code-type: arithmetic
    #  登录图形验证码有效时间/分钟
    expiration: 2
    #  验证码高度
    width: 111
    #  验证码宽度
    heigth: 36
    # 内容长度
    length: 2
    # 字体名称，为空则使用默认字体
    font-name:
    # 字体大小
    font-size: 25


#jwt
jwt:
  header: Authorization
  # 令牌前缀
  token-start-with: Bearer
  # 必须使用最少88位的Base64对该令牌进行编码
  secret: ZmQ0ZGI5NjQ0MDQwY2I4MjMxY2Y3ZmI3MjdhN2ZmMjNhODViOTg1ZGE0NTBjMGM4NDA5NzYxMjdjOWMwYWRmZTBlZjlhNGY3ZTg4Y2U3YTE1ODVkZDU5Y2Y3OGYwZWE1NzUzNWQ2YjFjZDc0NGMxZWU2MmQ3MjY1NzJmNTE0MzI=
  # 令牌过期时间 此处单位/毫秒 ，默认4小时，可在此网站生成 https://www.convertworld.com/zh-hans/time/milliseconds.html
  expiration: 180000 #14400000
  # 在线用户key
  online-key: online-token-
  # 在线用户key-3天
  long-time-token: long-time-token-
  # 验证码
  code-key: code-key-
  # token 续期检查时间范围（默认30分钟，单位毫秒），在token即将过期的一段时间内用户操作了，则给用户的token续期
  detect: 1800000
  # 续期时间范围，默认1小时，单位毫秒
  renew: 3600000

pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql


rsa:
  private_key: MIICdgIBADANBgkqhkiG9w0BAQEFAASCAmAwggJcAgEAAoGBANIuOKo2b8xUtX7tUCVhrjDlk6vJYvc2ltQ1azQdf2+0xNp8CqWs1zGxFdwsFptsGc0HUB32GdVI+TSYK3gsObZbjMO8dY8RY90sNBdcxRP41238soYIDYIGiYJhMMsjFRdaqt+aFZF+CRdk8g3fqGtus5HIUjQBzP2TQks0IF5dAgMBAAECgYEAzphWZKFbpSqCuH/GLuhkE3YmgE5U9BD5kx/q/3AbSo8SjHwu7wkFAbhCd4fytNU+SzVr//dfDzJKmvMUj2xRUHEOfgspnxeDPwqoWSWrppFZymUK0v+wB+hE99t2uUmkhlG6Kl0sk9vguKNuZFNP6JHvSXazLe6aWPPnOvfxGhUCQQDy6YTTrIkFfjvEcWr3+oVS0aTvuEWKBudfmbqDi0ru2vAHGLRg2GFXWqg0tRuX0KcZ/0QQcqbMjcMS00QjjAKHAkEA3YE8aj88lr8h32VJHJOq6VcnVowJjc1pgzoX/M7jCBKvJfKd9oo4OngyAyg3EUZwV2QrrVsESgy3jM3Ry/v8+wJAc3BIgHPJNkQUUTn5NNnojEA3Gvk+iubXBBbBjYwf0z1WvnieGDwcnm/l6g57i31MPE2UYiCqZiGkqAigpCgAdwJAVrQApwILwGIeayhlXuc6bk3sGweDsdrm4zP5Mb71xTIzFuKKDHf8HH7x7KRwMbXlwX93TUskOawSqO3jojoHwwJAJXCNcATgrzznlq5KPmfXF826EWp9I4ot68mr8VjNOgtdhpGEYBfRf9CLQsjPz/trm+4rzCUyOyk8QkXAyqaDzg==
  public_key: MIGfMA0GCSqGSIb3DQEBAQUAA4GNADCBiQKBgQDSLjiqNm/MVLV+7VAlYa4w5ZOryWL3NpbUNWs0HX9vtMTafAqlrNcxsRXcLBabbBnNB1Ad9hnVSPk0mCt4LDm2W4zDvHWPEWPdLDQXXMUT+Ndt/LKGCA2CBomCYTDLIxUXWqrfmhWRfgkXZPIN36hrbrORyFI0Acz9k0JLNCBeXQIDAQAB